#+(or clasp ecl sbcl) :NIL-VECTORS-ARE-STRINGS
#+(or clasp ecl) :ALLOW-NIL-ARRAYS
#+(or clasp ecl) :MAKE-CONDITION-WITH-COMPOUND-NAME
#+(or clasp ecl) :NO-FLOATING-POINT-UNDERFLOW-BY-DEFAULT

#+sbcl PRINT.BACKQUOTE.RANDOM.1
#+sbcl PRINT.BACKQUOTE.RANDOM.2
#+sbcl PRINT.BACKQUOTE.RANDOM.3
#+sbcl PRINT.BACKQUOTE.RANDOM.4
#+sbcl PRINT.BACKQUOTE.RANDOM.5
#+sbcl PRINT.BACKQUOTE.RANDOM.10
#+sbcl PRINT.BACKQUOTE.RANDOM.11
#+sbcl PRINT.BACKQUOTE.RANDOM.13
#+sbcl PRINT.BACKQUOTE.RANDOM.14

#+(or abcl clasp ecl sbcl) FORMAT.E.26
#+clasp PRINT.DOUBLE-FLOAT.RANDOM
#+clasp PRINT.LONG-FLOAT.RANDOM
