(cl:in-package #:incless)

(defmethod print-object-using-client ((client standard-client) (vec vector) stream)
  (cond ((and (not *print-readably*)
              (eql 0 *print-level*))
         (write-char #\# stream))
        ((or *print-array* *print-readably*)
         (write-string "#(" stream)
         (loop :with *print-level* = (and *print-level* (max 0 (1- *print-level*)))
               :with l := (1- (length vec))
               :for i :below l
               :do (write-object client (aref vec i) stream)
                   (write-char #\Space stream)
               :finally (write-object client (aref vec l) stream))
         (write-string ")" stream))
        (t (write-string "#<" stream)
           (write-object client (type-of vec) stream)
           (write-string ">" stream)))
  vec)
