(in-package #:incless-implementation)

(defun print-character (client obj stream)
  (declare (ignore client))
  (if (or *print-escape* *print-readably*)
      (progn (write-string "#\\" stream)
             (if (and (standard-char-p obj) (not (or (char= obj #\Space)
                                                     (char= obj #\Newline))))
                 (write-char obj stream)
                 (write-string (char-name obj) stream)))
      (write-char obj stream)))
