(cl:in-package #:incless-implementation)

(defun print-pathname (client path stream)
  (let ((namestring (ignore-errors (namestring path))))
    (cond (namestring
           (when (or *print-escape* *print-readably*)
             (write-string "#P" stream))
           (incless:write-object client (namestring path) stream))
          (t
           (incless:write-unreadable-object client path stream t nil
                                            (lambda ()
                                              (incless:write-object client :host stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-host path) stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client :device stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-device path) stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client :directory stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-directory path) stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client :name stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-name path) stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client :type stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-type path) stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client :version stream)
                                              (write-char #\Space stream)
                                              (incless:write-object client (pathname-version path) stream)))))))
